<?php
require_once __DIR__.'/../../inc/db.php';
require_once __DIR__.'/../../inc/auth.php';
require_role(['Admin']);
if (session_status() === PHP_SESSION_NONE) session_start();

$q = "
SELECT l.log_id, l.account_type, l.created_at,
       cu.username AS created_username,
       bu.username AS by_username
FROM account_creation_log l
JOIN users cu ON cu.user_id = l.created_user_id
JOIN users bu ON bu.user_id = l.created_by_user_id
ORDER BY l.created_at DESC
LIMIT 300
";
$res = $mysqli->query($q);
?>
<div class="card border-0 shadow-sm">
  <div class="card-body">
    <h5 class="mb-3">Account Creation Log</h5>
    <div class="table-responsive">
      <table class="table table-sm table-striped table-bordered mb-0">
        <thead class="table-light">
          <tr>
            <th style="width:60px;">ID</th>
            <th>Account Type</th>
            <th>Created User</th>
            <th>Created By</th>
            <th>Timestamp</th>
          </tr>
        </thead>
        <tbody class="small">
          <?php if ($res && $res->num_rows): while($r=$res->fetch_assoc()): ?>
          <tr>
            <td><?php echo (int)$r['log_id']; ?></td>
            <?php
              $type = (string)($r['account_type'] ?? '');
              $typeClass = match ($type) {
                'BHW' => 'primary',
                'BNS' => 'warning',
                'Parent' => 'secondary',
                default => 'secondary',
              };
            ?>
            <td>
              <span class="badge bg-<?php echo $typeClass; ?>">
                <?php echo htmlspecialchars($type); ?>
              </span>
            </td>
            <td><?php echo htmlspecialchars($r['created_username']); ?></td>
            <td><?php echo htmlspecialchars($r['by_username']); ?></td>
            <td><?php echo htmlspecialchars($r['created_at']); ?></td>
          </tr>
          <?php endwhile; else: ?>
          <tr><td colspan="5" class="text-center py-4">No log records found.</td></tr>
          <?php endif; ?>
        </tbody>
      </table>
    </div>
    <p class="small text-muted mt-2 mb-0">Automatically generated by trigger log_account_creation.</p>
  </div>
</div>